# Copyright 2025 Google LLC
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file or at
# https://developers.google.com/open-source/licenses/bsd

[build-system]
requires = [
    "scikit-build-core>=0.12.2,<1",
    "antlr4-tools>=0.2.0,<1",
    "grpcio-tools>=1.62.0,<2",
]
build-backend = "scikit_build_core.build"

[project]
name = "vanir"
version = "1.1.0"
authors = [
    { name = "Hyunwook (Wooky) Baek", email = "baekhw@google.com" },
    { name = "Duy Truong", email = "duytruong@google.com" },
    { name = "Justin Dunlap", email = "justindunlap@google.com" },
]
maintainers = [
    { name = "Hyunwook (Wooky) Baek", email = "baekhw@google.com" },
    { name = "Duy Truong", email = "duytruong@google.com" },
    { name = "Justin Dunlap", email = "justindunlap@google.com" },
]
description = """\
Vanir is a source code-based static analysis tool that automatically \
identifies the list of missing security patches in the target system. \
"""
readme = "README.md"
# This license only applies to precompiled packages of Vanir that includes
# FuzzyC.
license = "GPL-3.0-only"
requires-python = "<3.14,>=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Operating System :: POSIX :: Linux",
    "Topic :: Security",
]
keywords = [
  "static analysis",
  "source code analysis",
  "missing patch scanner",
]
dependencies = [
    # Keep only direct dependencies here, same as those mentioned in the
    # requirements.txt file. The dependencies here are kept at least on the same
    # version as present in the requirements_lock files and less than the next
    # major version to ensure compatibility.
    # Ref: https://packaging.python.org/en/latest/discussions/versioning/#semantic-versioning.
    "absl-py>=2.4.0,<3",
    "google-api-core[grpc]>=2.31.0,<3",
    "google-auth>=2.53.0,<3",
    "google-cloud-iam>=2.23.0,<3",

    # PiPs dependency resolution resolves to different major versions for
    # google-cloud-storage(v2.19.0 for Python 3.11, 3.12 and v3.9.0 for Python
    # 3.10 and 3.13) for different Python versions, hence keep the version
    # upper limit as 4 to keep the version range inclusive and simple.
    "google-cloud-storage>=3.11.0,<4",

    "jinja2>=3.1.6,<4",
    "jsonpath_ng>=1.8.0,<2",
    "mmh3>=5.2.1,<6",

    "protobuf>=7.35.1,<8",
    "python-dateutil>=2.9.0.post0,<3",
    "requests>=2.34.2,<3",
    "tenacity>=9.1.4,<10",
    "typing-extensions>=4.15.0,<5",
    "unidiff>=0.7.5,<1",
]

[project.urls]
Homepage = "https://github.com/google/vanir"
Issues = "https://github.com/google/vanir/issues"

[tool.scikit-build]
cmake.build-type = "Release"
cmake.source-dir = "vanir"
logging.level = "INFO"
sdist.exclude = ["dist/**", "**/*.bazel", "**/*.bzl"]

[tool.cibuildwheel]
test-command = "python -m vanir.pip_modules.pip_test_runner"

[tool.cibuildwheel.linux]
# Enabling only 'x86_64' and 'aarch64' manylinux architectures.
# Skipping musllinux and other manylinux architectures.
archs = ["x86_64", "aarch64"]
skip = "*-musllinux*"
# Install JDK 11 in Docker containers used by cibuildwheel. This is required by
# ANTLR4 commands that are run to generate CPP files from ANTLR4 grammar files
# and used in Python extension modules. 'antlr4-tools' seems to try to install
# JDK 11 if JDK 11 is not installed but that process is quite slow hence
# explicitly installing JDK 11 with 'yum' command.
before-all = "yum install -y java-11-openjdk-devel"
