# Copyright 2023 Google LLC
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file or at
# https://developers.google.com/open-source/licenses/bsd

# Java parser for Vanir based on Antlr4 upstream optimized Java
# grammar; written in C++.

load("@rules_cc//cc:defs.bzl", "cc_library")
load("@rules_python//python:defs.bzl", "py_library", "py_test")

load(":antlr4.external.bzl", "gen_java_parsers")

package(
    default_applicable_licenses = ["//:license"],
    default_visibility = ["//visibility:public"],
)

gen_java_parsers()

cc_library(
    name = "parser_core",
    srcs = ["parser_core.cc"],
    hdrs = ["parser_core.h"],
    copts = [
        # fexception is needed only for catching Antlr4 exceptions.
        "-fexceptions",
    ],
    features = ["-use_header_modules"],
    deps = [
        ":java_cc_lexer",
        ":java_cc_parser",
        "@com_google_absl//absl/log:check",
        "@com_google_absl//absl/status",
        "@com_google_absl//absl/status:statusor",
        "@com_google_absl//absl/strings",
    ],
)

py_library(
    name = "java_parser",
    srcs = ["java_parser.py"],
    data = [
        "//vanir/language_parsers/java/python:parser_core.so",
        "@pybind11_abseil//pybind11_abseil:status.so",
    ],
    deps = [
        "//vanir/language_parsers:abstract_language_parser",
        "//vanir/language_parsers:common",
    ],
)

py_test(
    name = "java_parser_test",
    size = "small",
    srcs = ["java_parser_test.py"],
    data = ["@pybind11_abseil//pybind11_abseil:status.so"],
    deps = [
        ":java_parser",
        "//vanir/language_parsers:abstract_language_parser",
        "//vanir/language_parsers:common",
        "@com_google_absl_py//absl/logging",
        "@com_google_absl_py//absl/testing:absltest",
    ],
)
